return {
  select = {
    preview = false,
    layout = {
      backdrop = false,
      row = 0.4,
      width = 0.7,
      min_width = 80,
      height = 0.4,
      min_height = 3,
      box = "vertical",
      border = "rounded",
      title = "{title}",
      title_pos = "center",
      { win = "input", height = 1, border = "bottom" },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
  dropdown = {
    layout = {
      backdrop = false,
      row = -1,
      width = 0.85,
      min_width = 80,
      height = 0.9,
      border = "none",
      box = "vertical",
      { win = "preview", title = "{preview}", height = 0.45, border = "rounded" },
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        title_pos = "center",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = "none" },
      },
    },
  },
  dropdown_pick = {
    layout = {
      backdrop = false,
      row = -1,
      width = 0.75,
      min_width = 80,
      height = 0.4,
      border = "none",
      box = "vertical",
      -- { win = "preview", title = "{preview}", height = 0.5, border = "single" },
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        title_pos = "center",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = "none" },
      },
    },
  },
  vscode = {
    preview = false,
    layout = {
      backdrop = false,
      row = 0.4,
      width = 0.7,
      min_width = 80,
      height = 0.4,
      border = "none",
      box = "vertical",
      {
        win = "input",
        height = 1,
        border = "rounded",
        title = "{title} {live} {flags}",
        title_pos = "center",
      },
      { win = "list", border = "hpad" },
      { win = "preview", title = "{preview}", border = "rounded" },
    },
  },
  ivy = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      width = 0,
      height = 0.35,
      border = "top",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
      },
    },
  },
  ivy_preview = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      width = 0,
      height = 0.45,
      border = "top",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
        { win = "preview", title = "{preview}", width = 0.5, border = "left" },
      },
    },
  },
  ivy_border = {
    layout = {
      box = "horizontal",
      row = -1,
      width = 0,
      min_width = 120,
      height = 0.35,
      backdrop = false,
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = false },
      },
      { win = "preview", title = "{preview}", border = "rounded", width = 0.45 },
    },
  },
  right = {
    preview = "main",
    layout = {
      backdrop = false,
      width = 40,
      min_width = 40,
      height = 0,
      position = "right",
      border = "none",
      box = "vertical",
      {
        win = "input",
        height = 1,
        border = true,
        title = "{title} {live} {flags}",
        title_pos = "center",
      },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
}
